#!/usr/bin/env python3
"""Capture the production MCP tool surface into datasets/tool_surface.json.

The snapshot is what run metadata counts tools against (``tool_count_effective``
in each run's wiring) and what the run pin compares its ``source_commit`` to, so a
stale snapshot shows up as ``tool_surface_stale`` rather than as a silent mismatch.

Run it after pulling condor:

    make tool-surface                    # uses ../condor
    CONDOR_PATH=/path/to/condor make tool-surface

Requires the condor repo checked out and its `uv` environment usable, since it
launches the real servers over stdio and asks them to list their tools.
"""
from __future__ import annotations

import asyncio
import json
import os
import subprocess
import sys
from datetime import date
from pathlib import Path

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "datasets" / "tool_surface.json"

# server label in the snapshot -> module the real server is launched as
SERVERS = {
    "mcp-hummingbot": "mcp_servers.hummingbot_api",
    "condor": "mcp_servers.condor",
}


def condor_repo() -> Path:
    """Resolve through config.condor_path() so every drift check reads one checkout.

    With more than one condor clone around, a script with its own resolution rule
    can capture the surface from one checkout while live runs use another — and
    the snapshot then "proves" a surface production doesn't have.
    """
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from config import condor_path

    path = condor_path()
    if path is None or not (path / "mcp_servers").is_dir():
        sys.exit(
            "No condor checkout found. Set CONDOR_PATH to the condor repo root "
            f"(tried: {os.environ.get('CONDOR_PATH') or os.environ.get('CONDOR_REPO') or ROOT.parent / 'condor'})."
        )
    print(f"using condor checkout: {path}", file=sys.stderr)
    return path


def head_commit(repo: Path) -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=repo,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown"


async def capture(repo: Path, module: str) -> dict[str, dict]:
    params = StdioServerParameters(
        command="uv",
        args=["run", "python", "-m", module],
        cwd=str(repo),
        env=dict(os.environ),
    )
    async with stdio_client(params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            tools = (await session.list_tools()).tools

    surface = {}
    for tool in tools:
        schema = tool.inputSchema or {}
        surface[tool.name] = {
            "required": sorted(schema.get("required") or []),
            "params": sorted((schema.get("properties") or {}).keys()),
        }
    return dict(sorted(surface.items()))


async def main() -> None:
    repo = condor_repo()
    snapshot = {
        "_comment": (
            "Generated by scripts/snapshot_tool_surface.py. Production MCP tool "
            "surface condor-bench records runs against. Do not hand-edit."
        ),
        "source_repo": "https://github.com/hummingbot/condor",
        "source_commit": head_commit(repo),
        "captured_at": date.today().isoformat(),
        "servers": {},
    }

    for label, module in SERVERS.items():
        print(f"capturing {label} ({module}) ...", file=sys.stderr)
        tools = await capture(repo, module)
        snapshot["servers"][label] = {"module": module, "tools": tools}
        print(f"  {len(tools)} tools", file=sys.stderr)

    SNAPSHOT.write_text(json.dumps(snapshot, indent=2) + "\n")
    print(f"wrote {SNAPSHOT.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    asyncio.run(main())
